# swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

#OpenAPI Docs
springdoc.api-docs.path=/v3/api-docs

# MailSender (Gmail SMTP - port 587 requires STARTTLS)
spring.config.import=optional:file:.env[.properties]
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Jwt
jwt.secret-key=very-secret-key-should-be-long-enough
jwt.access-token-expiration=3600000

# server
server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/habit
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
